In [64]:
import numpy as np
A=np.array([[2,1,-1],    [0,1,-4]])
B=np.array([[-2,1,0],    [-3,2,2]])
print("3A+2B = ", 3*A+2*B)
print("3A-2B = ", 3*A-2*B)
print("At.A = ", A.T @ A)
print("A.At = ",A @ A.T)

3A+2B =  [[ 2  5 -3]
 [-6  7 -8]]
3A-2B =  [[ 10   1  -3]
 [  6  -1 -16]]
At.A =  [[ 4  2 -2]
 [ 2  2 -5]
 [-2 -5 17]]
A.At =  [[ 6  5]
 [ 5 17]]


In [65]:
A=np.array([[4,0,5],[-1,3,2]])
B=np.array([[1,1,1],[3,5,7]])
C=np.array([[2,-3],[0,1]])
print("A+B = ", A + B)
print("A-B = ", A-B)
print("2A = ", 2*A)
print("-3B = ", -3*B)
print("2A-3B = ", 2*A - 3*B)
print("At.C = ", A.T@C)
print("C.A+B = ", C@A+B)
print("(C.A)t-2Bt = ", (C@A).T - 2*B.T)

A+B =  [[5 1 6]
 [2 8 9]]
A-B =  [[ 3 -1  4]
 [-4 -2 -5]]
2A =  [[ 8  0 10]
 [-2  6  4]]
-3B =  [[ -3  -3  -3]
 [ -9 -15 -21]]
2A-3B =  [[  5  -3   7]
 [-11  -9 -17]]
At.C =  [[  8 -13]
 [  0   3]
 [ 10 -13]]
C.A+B =  [[12 -8  5]
 [ 2  8  9]]
(C.A)t-2Bt =  [[  9  -7]
 [-11  -7]
 [  2 -12]]


In [66]:
print("a = ", np.array([[1,-3,2],[3,-4,1],[2,-5,3]])
      @np.array([[2,5,6],[1,2,5],[1,3,2]]))
print("b = ", np.array([[5,0,2,3],[4,1,5,3],[3,1,-1,2]])
      @np.array([[6],[-2],[7],[4]]))
print("d = ", np.array([[3,1,1],[2,1,2],[1,2,3]])
      @np.array([[1,1,-1],[2,-1,1],[1,0,1]]))
print("e = ", np.array([[1,2,1],[0,1,2],[3,1,1]])
      @np.array([[2,3,1],[-1,1,0],[1,2,-1]])
      @np.array([[1,2,1],[0,1,2],[3,1,1]]))


a =  [[ 1  5 -5]
 [ 3 10  0]
 [ 2  9 -7]]
b =  [[56]
 [69]
 [17]]
d =  [[ 6  2 -1]
 [ 6  1  1]
 [ 8 -1  4]]
e =  [[ 1  9 15]
 [-5  5  9]
 [12 26 32]]


In [67]:
A = np.array([[0,1,0],[0,0,1],[0,0,0]])
print("A^2 = ", A@A)
print("A^3 = ", A@A@A)
B = np.array([[1,2,1],[0,1,2],[3,1,1]])
print("B^2 = ", B@B)
C = np.array([[2,1],[1,3]])
print("C^3 = ", C@C@C)
print("D = [[1,n]\n"
      "[0,1]]")

A^2 =  [[0 0 1]
 [0 0 0]
 [0 0 0]]
A^3 =  [[0 0 0]
 [0 0 0]
 [0 0 0]]
B^2 =  [[4 5 6]
 [6 3 4]
 [6 8 6]]
C^3 =  [[15 20]
 [20 35]]
D = [[1,n]
[0,1]]


In [68]:
A=np.array([[1,2],[4,-1]])
B=np.array([[2,-3],[-4,1]])
print("a) = ", A@B - B@A)
A=np.array([[1,1,1],[0,1,1],[0,0,1]])
B=np.array([[7,5,3],[0,7,5],[0,0,7]])
print("c) = ", A@B - B@A)

a) =  [[ 4 -8]
 [12 -4]]
c) =  [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [78]:
A=np.array([[1,0,3],[2,1,1],[3,2,2]])
print("a) = ", np.linalg.inv(A))
B=np.array([[1,3,2],[2,1,3],[3,2,1]])
print("b) = ", np.linalg.inv(B))
C=np.array([[-1,1,1,1],[1,-1,1,1],[1,1,-1,1],[1,1,1,-1]])
print("c) = ", np.linalg.inv(C))
D=np.array([[0,1,1,1],[-1,0,1,1],[-1,-1,0,1],[-1,-1,-1,0]])
print("d) = ", np.linalg.inv(D))
print("e=\n"
            "[[1,-1,0,0,...,0]\n"
            "[0,1,-1,0,...,0]\n"
            "[0,0,1,-1,...,0]\n"
            "...............\n"
            "[0,0,0,0,...,1]]")

a) =  [[ 1.48029737e-16  2.00000000e+00 -1.00000000e+00]
 [-3.33333333e-01 -2.33333333e+00  1.66666667e+00]
 [ 3.33333333e-01 -6.66666667e-01  3.33333333e-01]]
b) =  [[-0.27777778  0.05555556  0.38888889]
 [ 0.38888889 -0.27777778  0.05555556]
 [ 0.05555556  0.38888889 -0.27777778]]
c) =  [[-0.25  0.25  0.25  0.25]
 [ 0.25 -0.25  0.25  0.25]
 [ 0.25  0.25 -0.25  0.25]
 [ 0.25  0.25  0.25 -0.25]]
d) =  [[-0. -1.  1. -1.]
 [ 1.  0. -1.  1.]
 [-1.  1. -0. -1.]
 [ 1. -1.  1.  0.]]
e=
[[1,-1,0,0,...,0]
[0,1,-1,0,...,0]
[0,0,1,-1,...,0]
...............
[0,0,0,0,...,1]]
