<a href="https://colab.research.google.com/github/KMSBismarck1402/IT/blob/main/python/NB_TextClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline
import numpy
import matplotlib.pyplot as plt
# import seaborn as sns; sns.set()
from sklearn.datasets import fetch_20newsgroups
data = fetch_20newsgroups()
data.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [ ]:
categories = data.target_names
train = fetch_20newsgroups(subset='train', categories=categories)
test = fetch_20newsgroups(subset='test', categories=categories)

print(len(train.data))
print(len(test.data))
print(train.target)

11314
7532
[7 4 4 ... 3 1 8]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

# Creating a model based on Multinomial Naive Bayes
model = make_pipeline(TfidfVectorizer(), MultinomialNB())

# Training the model with the train data
model.fit(train.data, train.target)

# Creating labels for the test data
labels = model.predict(test.data)

print(labels)
print(train.target)

[ 7 11  0 ...  9  3 15]
[7 4 4 ... 3 1 8]


In [ ]:
# Creating confusion matrix and heat map
# from sklearn.metrics import confusion_matrix
# mat = confusion_matrix(test.target, labels)
# sns.heatmap(mat.T, square=True, annot=True, fmt='d', cbar=False, xticklabels=train.target_names, yticklabels=train.target_names)

# # Ploting Heatmap of Confusion Matrix
# plt.xlabel('true label')
# plt.ylabel('predicted label')

In [ ]:
# Predicting category on new data based on trained model
def predict_categoory(s, train=train, model=model):
  pred = model.predict([s])
  return train.target_names[pred[0]]

In [ ]:
predict_categoory('Jesus Christ')

'soc.religion.christian'

In [ ]:
predict_categoory('Sending load to Internal Space Station')

'sci.space'

In [ ]:
predict_categoory('Suzuki Hayabusa is a very fast motorcycle')

'rec.motorcycles'

In [ ]:
predict_categoory('Audi is cheaper than BMW')

'rec.autos'

In [ ]:
predict_categoory('President of Vietnam')

'talk.politics.misc'