<a href="https://colab.research.google.com/github/KMSBismarck1402/IT/blob/main/python/GoogleColab/CNN_GoogleColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#https://www.studocu.com/vn/document/hoc-vien-ngan-hang/hoc-vien-ngan-hang/chuong-6-huong-dan-thuc-hanh-nhan-dien-anh-cnn/27469997
import tensorflow as tf
from tensorflow import keras
from keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
import numpy as np

In [15]:
from traitlets.traitlets import validate
import os
train_image_files_path = 'train'
valid_image_files_path = 'valid'

In [16]:
label =['apple', 'banana']

In [17]:
train_data_gen = ImageDataGenerator(rescale = 1/255)
valid_data_gen = ImageDataGenerator(rescale = 1/255)
train_generator = train_data_gen.flow_from_directory(
    train_image_files_path,
    target_size = (50,50),
    class_mode = 'categorical'
)
valid_generator = train_data_gen.flow_from_directory(
    valid_image_files_path,
    target_size = (50,50),
    class_mode = 'categorical'
)

Found 143 images belonging to 2 classes.
Found 19 images belonging to 2 classes.


In [18]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Flatten

model = tf.keras.models.Sequential()

#CNN1 Layer
model.add(Conv2D(32,(3,3), activation = 'relu', input_shape = (50,50,3)))
model.add(MaxPooling2D(2,2))

#CNN2 Layer
model.add(Conv2D(64,(3,3), activation = 'relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())

#Hidden layer
model.add(Dense(512, activation = tf.nn.relu))

#Output layer: 2 categories
model.add(Dense(2, activation = tf.nn.softmax))


In [20]:
from keras.optimizers import RMSprop
model.compile(optimizer = RMSprop(learning_rate = 0.001),
              loss = 'categorical_crossentropy',
              metrics= ['acc'])

In [21]:
EPOCHS = 10
history = model.fit(
    train_generator,
    steps_per_epoch=2,
    epochs= EPOCHS,
    verbose = 1,
    validation_data = valid_generator,
    validation_steps = 1
)

Epoch 1/10


c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\Image.py:992: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


2/2 [==============================] - 3s 2s/step - loss: 2.0537 - acc: 0.5156 - val_loss: 0.8511 - val_acc: 0.5263
Epoch 2/10
2/2 [==============================] - 2s 1s/step - loss: 0.7049 - acc: 0.4681 - val_loss: 0.6121 - val_acc: 0.8421
Epoch 3/10
2/2 [==============================] - 2s 766ms/step - loss: 0.5876 - acc: 0.8125 - val_loss: 0.5584 - val_acc: 0.5263
Epoch 4/10
2/2 [==============================] - 2s 1s/step - loss: 1.0139 - acc: 0.4468 - val_loss: 0.5744 - val_acc: 0.8947
Epoch 5/10
2/2 [==============================] - 2s 1s/step - loss: 0.5419 - acc: 0.8750 - val_loss: 0.4499 - val_acc: 0.8947
Epoch 6/10
2/2 [==============================] - 2s 954ms/step - loss: 0.4760 - acc: 0.8438 - val_loss: 0.4562 - val_acc: 0.8947
Epoch 7/10
2/2 [==============================] - 2s 1s/step - loss: 0.3930 - acc: 0.9062 - val_loss: 0.3062 - val_acc: 0.8947
Epoch 8/10
2/2 [==============================] - 1s 1s/step - loss: 0.6701 - acc: 0.5957 - val_loss: 0.8413 - val_a

In [25]:
from keras.preprocessing import image
import matplotlib.pyplot as plt
import matplotlib.image as mping

# Define your labels
labels = ['apple', 'banana']

# Specify the paths to your local image directories
train_image_files_path = 'train'
valid_image_files_path = 'valid'
# Variables to keep track of correct and total predictions
correct_predictions = 0
total_predictions = 0
# Load your model as needed
# model = load_your_model_here

# Function to predict and display images
def predict_and_display_images(image_directory):
    global correct_predictions
    global total_predictions
    for label in labels:
        label_path = os.path.join(image_directory, label)
        for fn in os.listdir(label_path):
            path = os.path.join(label_path, fn)

            # Display the image using Matplotlib
            #plt.imshow(mping.imread(path))
            #plt.show()

            # Load and preprocess the image using Keras
            img = image.load_img(path, target_size=(50, 50))
            x = image.img_to_array(img)
            x = x.reshape((1,) + x.shape)  # Reshape to (1, 50, 50, 3)
            y_predict = model.predict(x)
            print(y_predict)
            predicted_label = labels[np.argmax(y_predict)]
            #print(f'Predicted class: {predicted_label}')
            if predicted_label == label:
                correct_predictions += 1
            total_predictions += 1

# Run predictions for both training and validation data
predict_and_display_images(train_image_files_path)
predict_and_display_images(valid_image_files_path)
accuracy = (correct_predictions / total_predictions) * 100
print(f'Accuracy: {accuracy:.2f}%')

1/1 [==============================] - 0s 25ms/step
[[1. 0.]]
1/1 [==============================] - 0s 23ms/step
[[1. 0.]]
1/1 [==============================] - 0s 20ms/step
[[1. 0.]]
1/1 [==============================] - 0s 23ms/step
[[1. 0.]]
1/1 [==============================] - 0s 22ms/step
[[1. 0.]]
1/1 [==============================] - 0s 24ms/step
[[1. 0.]]
1/1 [==============================] - 0s 29ms/step
[[1. 0.]]
1/1 [==============================] - 0s 25ms/step
[[1. 0.]]
1/1 [==============================] - 0s 31ms/step
[[0. 1.]]
1/1 [==============================] - 0s 22ms/step
[[1. 0.]]
1/1 [==============================] - 0s 23ms/step
[[1.0000000e+00 1.1006263e-21]]
1/1 [==============================] - 0s 21ms/step
[[1. 0.]]
1/1 [==============================] - 0s 18ms/step
[[1. 0.]]
1/1 [==============================] - 0s 22ms/step
[[1. 0.]]
1/1 [==============================] - 0s 21ms/step
[[1. 0.]]
1/1 [==============================] - 0s 21ms/s